# Generated by Django 3.0.3 on 2020-03-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_book_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='likes',
        ),
    ]
